import discord
from discord.ext import commands

intents = discord.Intents.default()
intents.message_content = True
bot = commands.Bot(command_prefix='!', intents=intents)

@bot.command()
async def fakenuke(ctx):
  await ctx.send("NUKE SHOWTIME BEGINS") #you can add more of these if you wanna go to hell
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")
  await ctx.send("@here")

  bot.run("YOUR_TOKEN")
  await ctx.send("@here")
  await ctx.send("@here")
